#!/bin/sh

# all jar files in this dir are added to CLASSPATH
JARDIR=/usr/share/nicki/jars
# this directory is also in classpath
EXTRA_CLASSPATH_DIR=/usr/share/nicki/misc

MAIN=com.resare.nicki.NickiDaemon

CLASSPATH=$EXTRA_CLASSPATH_DIR
for jar in $JARDIR/*.jar
do
    CLASSPATH=$CLASSPATH:$jar
done

java -classpath $CLASSPATH $MAIN $@